name: 04 - Solicitud de mejora

on:
  push:
    paths:
      - "logs/mejora_04.txt"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notificar a equipo
        run: |
          echo "Solicitud de MEJORA detectada (por archivo logs/mejora_04.txt)"
          echo "Notificar a: DevA, DevB, IT1, IT2, Atención1, Atención2"
